paths:
  - repolocation: "/home/coder/lasersmart/"
    path: "builds/IHM/ihm.exe"
    url: "/url1"
  - repolocation: "/home/coder/lasersmart/"
    path: "builds/sbRIO-9651/home/lvuser/natinst/bin/startup.rtexe"
    url: "/url2"
